INSERT INTO institusi ( nama ) VALUES ( 
'FOREIGN INSTITUTIONS / PRIVATE INSTITUTION'); 
INSERT INTO institusi ( nama ) VALUES ( 
'GERMAN MALAYSIAN INSTITUTE'); 
INSERT INTO institusi ( nama ) VALUES ( 
'KOLEJ KEMAHIRAN TINGGI MARA'); 
INSERT INTO institusi ( nama ) VALUES ( 
'KOLEJ KOMUNITI'); 
INSERT INTO institusi ( nama ) VALUES ( 
'KOLEJ UNIVERSITI ISLAM ANTARABANGSA SELANGOR '); 
INSERT INTO institusi ( nama ) VALUES ( 
'KOLEJ UNIVERSITI ISLAM MALAYSIA'); 
INSERT INTO institusi ( nama ) VALUES ( 
'KOLEJ UNIVERSITI KEJURUTERAAN & TEKNOLOGI MALAYSIA'); 
INSERT INTO institusi ( nama ) VALUES ( 
'KOLEJ UNIVERSITI KEJURUTERAAN UTARA MALAYSIA'); 
INSERT INTO institusi ( nama ) VALUES ( 
'KOLEJ UNIVERSITI SAINS DAN TEKNOLOGI MALAYSIA'); 
INSERT INTO institusi ( nama ) VALUES ( 
'KOLEJ UNIVERSITI TEKNIKAL KEBANGSAAN MALAYSIA'); 
INSERT INTO institusi ( nama ) VALUES ( 
'KOLEJ UNIVERSITI TEKNOLOGI TUN HUSSEIN ONN'); 
INSERT INTO institusi ( nama ) VALUES ( 
'KUSZA'); 
INSERT INTO institusi ( nama ) VALUES ( 
'L&G-TWINTECH INSTITUTE OF TECHNOLOGY'); 
INSERT INTO institusi ( nama ) VALUES ( 
'LAIN-LAIN INSTITUSI'); 
INSERT INTO institusi ( nama ) VALUES ( 
'LAIN-LAIN IPTS'); 
INSERT INTO institusi ( nama ) VALUES ( 
'MAKTAB PERGURUAN'); 
INSERT INTO institusi ( nama ) VALUES ( 
'POLITEKNIK'); 
INSERT INTO institusi ( nama ) VALUES ( 
'POLITEKNIK BALIK PULAU'); 
INSERT INTO institusi ( nama ) VALUES ( 
'POLITEKNIK BANTING, SELANGOR'); 
INSERT INTO institusi ( nama ) VALUES ( 
'POLITEKNIK DUNGUN'); 
INSERT INTO institusi ( nama ) VALUES ( 
'POLITEKNIK HULU TERENGGANU'); 
INSERT INTO institusi ( nama ) VALUES ( 
'POLITEKNIK IBRAHIM SULTAN'); 
INSERT INTO institusi ( nama ) VALUES ( 
'POLITEKNIK IPOH'); 
INSERT INTO institusi ( nama ) VALUES ( 
'POLITEKNIK JELI'); 
INSERT INTO institusi ( nama ) VALUES ( 
'POLITEKNIK KOTA BHARU'); 
INSERT INTO institusi ( nama ) VALUES ( 
'POLITEKNIK KOTA KINABALU'); 
INSERT INTO institusi ( nama ) VALUES ( 
'POLITEKNIK KOTA MELAKA'); 
INSERT INTO institusi ( nama ) VALUES ( 
'POLITEKNIK KOTA, KUALA TERENGGANU'); 
INSERT INTO institusi ( nama ) VALUES ( 
'POLITEKNIK KUANTAN'); 
INSERT INTO institusi ( nama ) VALUES ( 
'POLITEKNIK KUCHING, SARAWAK'); 
INSERT INTO institusi ( nama ) VALUES ( 
'POLITEKNIK KULIM'); 
INSERT INTO institusi ( nama ) VALUES ( 
'POLITEKNIK MERLIMAU MELAKA'); 
INSERT INTO institusi ( nama ) VALUES ( 
'POLITEKNIK MERSING'); 
INSERT INTO institusi ( nama ) VALUES ( 
'POLITEKNIK METrO BETONG, SARAWAK'); 
INSERT INTO institusi ( nama ) VALUES ( 
'POLITEKNIK METrO JOHOR BAHRU'); 
INSERT INTO institusi ( nama ) VALUES ( 
'POLITEKNIK METrO KUALA LUMPUR'); 
INSERT INTO institusi ( nama ) VALUES ( 
'POLITEKNIK METrO KUANTAN'); 
INSERT INTO institusi ( nama ) VALUES ( 
'POLITEKNIK METrO TASEK GELUGOR, PULAU PINANG'); 
INSERT INTO institusi ( nama ) VALUES ( 
'POLITEKNIK MUADZAM SHAH'); 
INSERT INTO institusi ( nama ) VALUES ( 
'POLITEKNIK MUKAH SARAWAK'); 
INSERT INTO institusi ( nama ) VALUES ( 
'POLITEKNIK NILAI'); 
INSERT INTO institusi ( nama ) VALUES ( 
'POLITEKNIK PAGOH, JOHOR'); 
INSERT INTO institusi ( nama ) VALUES ( 
'POLITEKNIK PORT DICKSON'); 
INSERT INTO institusi ( nama ) VALUES ( 
'POLITEKNIK SANDAKAN, SABAH'); 
INSERT INTO institusi ( nama ) VALUES ( 
'POLITEKNIK SEBERANG PRAI'); 
INSERT INTO institusi ( nama ) VALUES ( 
'POLITEKNIK SHAH ALAM'); 
INSERT INTO institusi ( nama ) VALUES ( 
'POLITEKNIK SULTAN ABDUL HALIM MU''ADZAM SHAH'); 
INSERT INTO institusi ( nama ) VALUES ( 
'POLITEKNIK SULTAN AZLAN SHAH'); 
INSERT INTO institusi ( nama ) VALUES ( 
'POLITEKNIK SULTAN HJ AHMAD SHAH'); 
INSERT INTO institusi ( nama ) VALUES ( 
'POLITEKNIK SULTAN IDRIS SHAH'); 
INSERT INTO institusi ( nama ) VALUES ( 
'POLITEKNIK SULTAN MIZAN ZAINAL ABIDIN'); 
INSERT INTO institusi ( nama ) VALUES ( 
'POLITEKNIK SULTAN SALAHUDIN ABDUL AZIZ SHAH'); 
INSERT INTO institusi ( nama ) VALUES ( 
'POLITEKNIK TUANKU SULTANAH BAHIYAH'); 
INSERT INTO institusi ( nama ) VALUES ( 
'POLITEKNIK TUNKU SYED SIRAJUDDIN '); 
INSERT INTO institusi ( nama ) VALUES ( 
'POLITEKNIK UNGKU HALIM'); 
INSERT INTO institusi ( nama ) VALUES ( 
'POLITEKNIK UNGKU OMAR'); 
INSERT INTO institusi ( nama ) VALUES ( 
'POLY-TUAS'); 
INSERT INTO institusi ( nama ) VALUES ( 
'TIADA MAKLUMAT'); 
INSERT INTO institusi ( nama ) VALUES ( 
'UNIVERSITI DARUL IMAN MALAYSIA '); 
INSERT INTO institusi ( nama ) VALUES ( 
'UNIVERSITI ISLAM ANTARABANGSA MALAYSIA'); 
INSERT INTO institusi ( nama ) VALUES ( 
'UNIVERSITI KEBANGSAAN MALAYSIA'); 
INSERT INTO institusi ( nama ) VALUES ( 
'UNIVERSITI MALAYA'); 
INSERT INTO institusi ( nama ) VALUES ( 
'UNIVERSITI MALAYSIA KELANTAN'); 
INSERT INTO institusi ( nama ) VALUES ( 
'UNIVERSITI MALAYSIA PAHANG'); 
INSERT INTO institusi ( nama ) VALUES ( 
'UNIVERSITI MALAYSIA PERLIS'); 
INSERT INTO institusi ( nama ) VALUES ( 
'UNIVERSITI MALAYSIA SABAH'); 
INSERT INTO institusi ( nama ) VALUES ( 
'UNIVERSITI MALAYSIA SARAWAK'); 
INSERT INTO institusi ( nama ) VALUES ( 
'UNIVERSITI MALAYSIA TERENGGANU'); 
INSERT INTO institusi ( nama ) VALUES ( 
'UNIVERSITI MULTIMEDIA MALAYSIA'); 
INSERT INTO institusi ( nama ) VALUES ( 
'UNIVERSITI PENDIDIKAN SULTAN IDRIS'); 
INSERT INTO institusi ( nama ) VALUES ( 
'UNIVERSITI PERTAHANAN NASIONAL MALAYSIA'); 
INSERT INTO institusi ( nama ) VALUES ( 
'UNIVERSITI PERTANIAN MALAYSIA'); 
INSERT INTO institusi ( nama ) VALUES ( 
'UNIVERSITI PUTRA MALAYSIA'); 
INSERT INTO institusi ( nama ) VALUES ( 
'UNIVERSITI SAINS ISLAM MALAYSIA'); 
INSERT INTO institusi ( nama ) VALUES ( 
'UNIVERSITI SAINS MALAYSIA'); 
INSERT INTO institusi ( nama ) VALUES ( 
'UNIVERSITI SULTAN ZAINAL ABIDIN'); 
INSERT INTO institusi ( nama ) VALUES ( 
'UNIVERSITI TEKNIKAL MALAYSIA MELAKA'); 
INSERT INTO institusi ( nama ) VALUES ( 
'UNIVERSITI TEKNOLOGI MALAYSIA'); 
INSERT INTO institusi ( nama ) VALUES ( 
'UNIVERSITI TEKNOLOGI MARA (UITM)'); 
INSERT INTO institusi ( nama ) VALUES ( 
'UNIVERSITI TEKNOLOGI PETRONAS'); 
INSERT INTO institusi ( nama ) VALUES ( 
'UNIVERSITI TENAGA NASIONAL'); 
INSERT INTO institusi ( nama ) VALUES ( 
'UNIVERSITI TUN HUSSEIN ONN MALAYSIA'); 
INSERT INTO institusi ( nama ) VALUES ( 
'UNIVERSITI UTARA MALAYSIA'); 
commit;
 
